name: FOTOS Y VIDEOS DE BODA
favicon: null
layout_spectrum: 0.549913533963263
typography_spectrum: 0.2628
title: mucho más que reportajes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#f0f2d6'
    - '#86bfbc'
    - '#696e86'
    - '#48454a'
  brandStrength: 0
  lightness: 0.2231441684998572
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
