name: fotos de boda
favicon: null
layout_spectrum: 0.549913533963263
typography_spectrum: 0.6899460209533572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#f0f2d6'
    - '#86bfbc'
    - '#696e86'
    - '#48454a'
  brandStrength: 0.45264557329937816
  lightness: 0.2231441684998572
  saturation: 0.3674080832861364
  rhythmicContrast: 0.5829440467059612
purpose: []
